In [3]:
from keras.preprocessing.text import Tokenizer
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout, Embedding
from keras.utils import np_utils
from keras.utils import plot_model
from pickle import dump
from keras.utils import to_categorical
	
# Read sentences.
filename = 'rebuplic_preprocessed.txt'
file = open(filename, 'r')
data = file.read()
file.close()
lines = data.split('\n')

# Convert the words into integers.
t = Tokenizer()
t.fit_on_texts(lines)
encoded_lines = t.texts_to_sequences(lines)
vocab_size = len(t.word_index) + 1

# Split the data into X and y
encoded_lines = np.array(encoded_lines[:-1]) # Remove last line which is '\n'
X = encoded_lines[:,:-1]
y = encoded_lines[:,-1]
print (X)
print (y)
seq_length = len(X[1])

model = Sequential()
model.add(Embedding(vocab_size, 50, input_length = seq_length))
model.add(LSTM(200, return_sequences = True))
model.add(LSTM(200))
model.add(Dense(200, activation='relu'))
model.add(Dense(vocab_size, activation='sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print (model.summary())

y = to_categorical(y, num_classes = vocab_size)
model.fit(X,y,batch_size=128, epochs=100)

model.save('word_generation_100_epochs.h5')
dump(t, open('tokenizer.pkl', 'wb'))


[[673   5   5 ... 658  89   5]
 [  5   5 171 ...  89   5  35]
 [  5 171 280 ...   5  35 281]
 ...
 [ 12  66   4 ...   4 672   8]
 [ 66   4  92 ... 672   8   6]
 [  4  92  44 ...   8   6  21]]
[ 35 281  28 ...   6  21   9]
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 50, 50)            33700     
_________________________________________________________________
lstm_5 (LSTM)                (None, 50, 200)           200800    
_________________________________________________________________
lstm_6 (LSTM)                (None, 200)               320800    
_________________________________________________________________
dense_5 (Dense)              (None, 200)               40200     
_________________________________________________________________
dense_6 (Dense)              (None, 674)               135474    
Total params: 730,974
Trainabl

2558/2558 [==============================] - 61s 24ms/step - loss: 3.1802 - acc: 0.1814
Epoch 70/100
2558/2558 [==============================] - 63s 25ms/step - loss: 3.1486 - acc: 0.1767
Epoch 71/100
2558/2558 [==============================] - 62s 24ms/step - loss: 3.1113 - acc: 0.1888
Epoch 72/100
2558/2558 [==============================] - 61s 24ms/step - loss: 3.0930 - acc: 0.2009
Epoch 73/100
2558/2558 [==============================] - 61s 24ms/step - loss: 3.0636 - acc: 0.2005
Epoch 74/100
2558/2558 [==============================] - 62s 24ms/step - loss: 3.0601 - acc: 0.1955
Epoch 75/100
2558/2558 [==============================] - 63s 24ms/step - loss: 3.0121 - acc: 0.2142
Epoch 76/100
2558/2558 [==============================] - 62s 24ms/step - loss: 2.9929 - acc: 0.2201
Epoch 77/100
2558/2558 [==============================] - 64s 25ms/step - loss: 2.9601 - acc: 0.2236
Epoch 78/100
2558/2558 [==============================] - 62s 24ms/step - loss: 2.9330 - acc: 0.2244
Epo